# Generated by Django 5.1.6 on 2025-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('discriminator', models.CharField(max_length=4)),
                ('avatar', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField()),
                ('mfa_enabled', models.BooleanField()),
                ('flags', models.IntegerField()),
                ('public_flags', models.IntegerField()),
            ],
        ),
    ]
