# Generated by Django 5.1.6 on 2025-02-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discord_id', models.CharField(max_length=255, unique=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('engagement_zone', models.CharField(default='General', max_length=255)),
                ('monthly_score', models.IntegerField(default=0)),
            ],
        ),
    ]
