# Generated by Django 5.1.6 on 2025-02-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_badge'),
        ('users', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
